\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}


<<
require(RCurl)
states = read.csv(textConnection(getURL(URL)), colClass = c("character", "character"))

g = graph.data.frame(states, directed=F)
g.degree = degree(g)
g.degree [g.degree == max(g.degree)] 

g.shortestpath.m = shortest.paths(g)
str(g.shortestpath.m)
sorted.names = sort( rownames(g.shortestpath.m) )
gsm = g.shortestpath.m[, sorted.names]
gsm = gsm[sorted.names, ]

state.year.tb = read.csv(textConnection(getURL(URL2)), colClass = c("character", NA))
>>=

@




\end{document}