# This Makefile is for the Bio-Phylo extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.56 (Revision: 65600) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#

#   MakeMaker Parameters:

#     AUTHOR => q[Rutger Vos]
#     BUILD_REQUIRES => {  }
#     EXE_FILES => []
#     NAME => q[Bio-Phylo]
#     PL_FILES => {  }
#     PREREQ_PM => {  }
#     VERSION_FROM => q[lib/Bio/Phylo.pm]
#     clean => {  }
#     dist => { COMPRESS=>q[gzip -9f], SUFFIX=>q[gz] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /opt/local/lib/perl5/5.8.9/darwin-2level/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = /usr/bin/gcc-4.2
CCCDLFLAGS =  
CCDLFLAGS =  
DLEXT = bundle
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = env MACOSX_DEPLOYMENT_TARGET=10.3 /usr/bin/gcc-4.2
LDDLFLAGS = -L/opt/local/lib -arch x86_64 -bundle -undefined dynamic_lookup
LDFLAGS = -L/opt/local/lib -arch x86_64
LIBC = /usr/lib/libc.dylib
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = darwin
OSVERS = 10.2.0
RANLIB = ranlib
SITELIBEXP = /opt/local/lib/perl5/site_perl/5.8.9
SITEARCHEXP = /opt/local/lib/perl5/site_perl/5.8.9/darwin-2level
SO = dylib
VENDORARCHEXP = /opt/local/lib/perl5/vendor_perl/5.8.9/darwin-2level
VENDORLIBEXP = /opt/local/lib/perl5/vendor_perl/5.8.9


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = Bio-Phylo
NAME_SYM = Bio_Phylo
VERSION = 0.34
VERSION_MACRO = VERSION
VERSION_SYM = 0_34
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 0.34
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1pm
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /opt/local
SITEPREFIX = /opt/local
VENDORPREFIX = /opt/local
INSTALLPRIVLIB = /opt/local/lib/perl5/5.8.9
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /opt/local/lib/perl5/site_perl/5.8.9
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /opt/local/lib/perl5/vendor_perl/5.8.9
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /opt/local/lib/perl5/5.8.9/darwin-2level
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /opt/local/lib/perl5/site_perl/5.8.9/darwin-2level
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /opt/local/lib/perl5/vendor_perl/5.8.9/darwin-2level
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /opt/local/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /opt/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /opt/local/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /opt/local/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /opt/local/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /opt/local/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /opt/local/share/man/man1p
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /opt/local/share/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /opt/local/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /opt/local/share/man/man3p
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /opt/local/share/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /opt/local/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /opt/local/lib/perl5/5.8.9
PERL_ARCHLIB = /opt/local/lib/perl5/5.8.9/darwin-2level
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /opt/local/lib/perl5/5.8.9/darwin-2level/CORE
PERL = /opt/local/bin/perl
FULLPERL = /opt/local/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /opt/local/lib/perl5/5.8.9/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.56
MM_REVISION = 65600

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = Bio-Phylo
BASEEXT = Phylo
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = lib/Bio/Phylo.pm
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = lib/Bio/Phylo.pm \
	lib/Bio/Phylo/EvolutionaryModels.pm \
	lib/Bio/Phylo/Factory.pm \
	lib/Bio/Phylo/Forest.pm \
	lib/Bio/Phylo/Forest/DrawNode.pm \
	lib/Bio/Phylo/Forest/DrawTree.pm \
	lib/Bio/Phylo/Forest/Node.pm \
	lib/Bio/Phylo/Forest/Tree.pm \
	lib/Bio/Phylo/Generator.pm \
	lib/Bio/Phylo/IO.pm \
	lib/Bio/Phylo/Identifiable.pm \
	lib/Bio/Phylo/Listable.pm \
	lib/Bio/Phylo/Manual.pod \
	lib/Bio/Phylo/Matrices.pm \
	lib/Bio/Phylo/Matrices/Datatype.pm \
	lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	lib/Bio/Phylo/Matrices/Datum.pm \
	lib/Bio/Phylo/Matrices/Matrix.pm \
	lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	lib/Bio/Phylo/NeXML/DOM.pm \
	lib/Bio/Phylo/NeXML/DOM/Document.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	lib/Bio/Phylo/NeXML/DOM/Element.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	lib/Bio/Phylo/NeXML/Meta.pm \
	lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	lib/Bio/Phylo/NeXML/Writable.pm \
	lib/Bio/Phylo/Parsers/Abstract.pm \
	lib/Bio/Phylo/Parsers/Fasta.pm \
	lib/Bio/Phylo/Parsers/Newick.pm \
	lib/Bio/Phylo/Parsers/Nexml.pm \
	lib/Bio/Phylo/Parsers/Nexus.pm \
	lib/Bio/Phylo/Parsers/Phylip.pm \
	lib/Bio/Phylo/Parsers/Table.pm \
	lib/Bio/Phylo/Parsers/Taxlist.pm \
	lib/Bio/Phylo/Parsers/Tolweb.pm \
	lib/Bio/Phylo/Project.pm \
	lib/Bio/Phylo/Set.pm \
	lib/Bio/Phylo/Taxa.pm \
	lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	lib/Bio/Phylo/Taxa/Taxon.pm \
	lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	lib/Bio/Phylo/Treedrawer.pm \
	lib/Bio/Phylo/Treedrawer/Abstract.pm \
	lib/Bio/Phylo/Treedrawer/Canvas.pm \
	lib/Bio/Phylo/Treedrawer/Gif.pm \
	lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	lib/Bio/Phylo/Treedrawer/Pdf.pm \
	lib/Bio/Phylo/Treedrawer/Png.pm \
	lib/Bio/Phylo/Treedrawer/Svg.pm \
	lib/Bio/Phylo/Treedrawer/Swf.pm \
	lib/Bio/Phylo/Unparsers/Abstract.pm \
	lib/Bio/Phylo/Unparsers/Mrp.pm \
	lib/Bio/Phylo/Unparsers/Newick.pm \
	lib/Bio/Phylo/Unparsers/Nexml.pm \
	lib/Bio/Phylo/Unparsers/Nexus.pm \
	lib/Bio/Phylo/Unparsers/Pagel.pm \
	lib/Bio/Phylo/Unparsers/Phylip.pm \
	lib/Bio/Phylo/Util/CONSTANT.pm \
	lib/Bio/Phylo/Util/Exceptions.pm \
	lib/Bio/Phylo/Util/IDPool.pm \
	lib/Bio/Phylo/Util/Logger.pm \
	lib/Bio/Phylo/Util/StackTrace.pm

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/Bio/Phylo.pm \
	lib/Bio/Phylo/EvolutionaryModels.pm \
	lib/Bio/Phylo/Factory.pm \
	lib/Bio/Phylo/Forest.pm \
	lib/Bio/Phylo/Forest/DrawNode.pm \
	lib/Bio/Phylo/Forest/DrawTree.pm \
	lib/Bio/Phylo/Forest/Node.pm \
	lib/Bio/Phylo/Forest/Tree.pm \
	lib/Bio/Phylo/Generator.pm \
	lib/Bio/Phylo/IO.pm \
	lib/Bio/Phylo/Identifiable.pm \
	lib/Bio/Phylo/Listable.pm \
	lib/Bio/Phylo/Manual.pod \
	lib/Bio/Phylo/Matrices.pm \
	lib/Bio/Phylo/Matrices/Datatype.pm \
	lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	lib/Bio/Phylo/Matrices/Datum.pm \
	lib/Bio/Phylo/Matrices/Matrix.pm \
	lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	lib/Bio/Phylo/NeXML/DOM.pm \
	lib/Bio/Phylo/NeXML/DOM/Document.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	lib/Bio/Phylo/NeXML/DOM/Element.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	lib/Bio/Phylo/NeXML/Meta.pm \
	lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	lib/Bio/Phylo/NeXML/Writable.pm \
	lib/Bio/Phylo/Parsers/Abstract.pm \
	lib/Bio/Phylo/Parsers/Fasta.pm \
	lib/Bio/Phylo/Parsers/Newick.pm \
	lib/Bio/Phylo/Parsers/Nexml.pm \
	lib/Bio/Phylo/Parsers/Nexus.pm \
	lib/Bio/Phylo/Parsers/Phylip.pm \
	lib/Bio/Phylo/Parsers/Table.pm \
	lib/Bio/Phylo/Parsers/Taxlist.pm \
	lib/Bio/Phylo/Parsers/Tolweb.pm \
	lib/Bio/Phylo/Project.pm \
	lib/Bio/Phylo/Set.pm \
	lib/Bio/Phylo/Taxa.pm \
	lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	lib/Bio/Phylo/Taxa/Taxon.pm \
	lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	lib/Bio/Phylo/Treedrawer.pm \
	lib/Bio/Phylo/Treedrawer/Abstract.pm \
	lib/Bio/Phylo/Treedrawer/Canvas.pm \
	lib/Bio/Phylo/Treedrawer/Gif.pm \
	lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	lib/Bio/Phylo/Treedrawer/Pdf.pm \
	lib/Bio/Phylo/Treedrawer/Png.pm \
	lib/Bio/Phylo/Treedrawer/Svg.pm \
	lib/Bio/Phylo/Treedrawer/Swf.pm \
	lib/Bio/Phylo/Unparsers/Abstract.pm \
	lib/Bio/Phylo/Unparsers/Mrp.pm \
	lib/Bio/Phylo/Unparsers/Newick.pm \
	lib/Bio/Phylo/Unparsers/Nexml.pm \
	lib/Bio/Phylo/Unparsers/Nexus.pm \
	lib/Bio/Phylo/Unparsers/Pagel.pm \
	lib/Bio/Phylo/Unparsers/Phylip.pm \
	lib/Bio/Phylo/Util/CONSTANT.pm \
	lib/Bio/Phylo/Util/Exceptions.pm \
	lib/Bio/Phylo/Util/IDPool.pm \
	lib/Bio/Phylo/Util/Logger.pm \
	lib/Bio/Phylo/Util/StackTrace.pm

PM_TO_BLIB = lib/Bio/Phylo/Parsers/Abstract.pm \
	blib/lib/Bio/Phylo/Parsers/Abstract.pm \
	lib/Bio/Phylo/Forest/Node.pm \
	blib/lib/Bio/Phylo/Forest/Node.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	lib/Bio/Phylo/Util/IDPool.pm \
	blib/lib/Bio/Phylo/Util/IDPool.pm \
	lib/Bio/Phylo/Taxa/Taxon.pm \
	blib/lib/Bio/Phylo/Taxa/Taxon.pm \
	lib/Bio/Phylo/Taxa.pm \
	blib/lib/Bio/Phylo/Taxa.pm \
	lib/Bio/Phylo/Unparsers/Mrp.pm \
	blib/lib/Bio/Phylo/Unparsers/Mrp.pm \
	lib/Bio/Phylo/EvolutionaryModels.pm \
	blib/lib/Bio/Phylo/EvolutionaryModels.pm \
	lib/Bio/Phylo/Parsers/Phylip.pm \
	blib/lib/Bio/Phylo/Parsers/Phylip.pm \
	lib/Bio/Phylo/IO.pm \
	blib/lib/Bio/Phylo/IO.pm \
	lib/Bio/Phylo/Treedrawer/Canvas.pm \
	blib/lib/Bio/Phylo/Treedrawer/Canvas.pm \
	lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	lib/Bio/Phylo/Util/Exceptions.pm \
	blib/lib/Bio/Phylo/Util/Exceptions.pm \
	lib/Bio/Phylo/Util/CONSTANT.pm \
	blib/lib/Bio/Phylo/Util/CONSTANT.pm \
	lib/Bio/Phylo/Unparsers/Nexml.pm \
	blib/lib/Bio/Phylo/Unparsers/Nexml.pm \
	lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	blib/lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	lib/Bio/Phylo/Parsers/Table.pm \
	blib/lib/Bio/Phylo/Parsers/Table.pm \
	lib/Bio/Phylo/Matrices/Matrix.pm \
	blib/lib/Bio/Phylo/Matrices/Matrix.pm \
	lib/Bio/Phylo/Treedrawer/Pdf.pm \
	blib/lib/Bio/Phylo/Treedrawer/Pdf.pm \
	lib/Bio/Phylo/Listable.pm \
	blib/lib/Bio/Phylo/Listable.pm \
	lib/Bio/Phylo/Generator.pm \
	blib/lib/Bio/Phylo/Generator.pm \
	lib/Bio/Phylo/Matrices/Datatype.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype.pm \
	lib/Bio/Phylo/Treedrawer/Svg.pm \
	blib/lib/Bio/Phylo/Treedrawer/Svg.pm \
	lib/Bio/Phylo/Util/StackTrace.pm \
	blib/lib/Bio/Phylo/Util/StackTrace.pm \
	lib/Bio/Phylo/Parsers/Tolweb.pm \
	blib/lib/Bio/Phylo/Parsers/Tolweb.pm \
	lib/Bio/Phylo/NeXML/DOM/Document.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Document.pm \
	lib/Bio/Phylo/Treedrawer.pm \
	blib/lib/Bio/Phylo/Treedrawer.pm \
	lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	lib/Bio/Phylo.pm \
	blib/lib/Bio/Phylo.pm \
	lib/Bio/Phylo/Forest/Tree.pm \
	blib/lib/Bio/Phylo/Forest/Tree.pm \
	lib/Bio/Phylo/Unparsers/Nexus.pm \
	blib/lib/Bio/Phylo/Unparsers/Nexus.pm \
	lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	lib/Bio/Phylo/Identifiable.pm \
	blib/lib/Bio/Phylo/Identifiable.pm \
	lib/Bio/Phylo/Forest/DrawTree.pm \
	blib/lib/Bio/Phylo/Forest/DrawTree.pm \
	lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	lib/Bio/Phylo/Util/Logger.pm \
	blib/lib/Bio/Phylo/Util/Logger.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	lib/Bio/Phylo/Unparsers/Abstract.pm \
	blib/lib/Bio/Phylo/Unparsers/Abstract.pm \
	lib/Bio/Phylo/Forest.pm \
	blib/lib/Bio/Phylo/Forest.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	lib/Bio/Phylo/Parsers/Nexus.pm \
	blib/lib/Bio/Phylo/Parsers/Nexus.pm \
	lib/Bio/Phylo/Matrices.pm \
	blib/lib/Bio/Phylo/Matrices.pm \
	lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	blib/lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	lib/Bio/Phylo/Treedrawer/Swf.pm \
	blib/lib/Bio/Phylo/Treedrawer/Swf.pm \
	lib/Bio/Phylo/NeXML/DOM.pm \
	blib/lib/Bio/Phylo/NeXML/DOM.pm \
	lib/Bio/Phylo/Project.pm \
	blib/lib/Bio/Phylo/Project.pm \
	lib/Bio/Phylo/Manual.pod \
	blib/lib/Bio/Phylo/Manual.pod \
	lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	lib/Bio/Phylo/Parsers/Fasta.pm \
	blib/lib/Bio/Phylo/Parsers/Fasta.pm \
	lib/Bio/Phylo/Treedrawer/Png.pm \
	blib/lib/Bio/Phylo/Treedrawer/Png.pm \
	lib/Bio/Phylo/Parsers/Newick.pm \
	blib/lib/Bio/Phylo/Parsers/Newick.pm \
	lib/Bio/Phylo/Set.pm \
	blib/lib/Bio/Phylo/Set.pm \
	lib/Bio/Phylo/Unparsers/Phylip.pm \
	blib/lib/Bio/Phylo/Unparsers/Phylip.pm \
	lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	lib/Bio/Phylo/NeXML/Meta.pm \
	blib/lib/Bio/Phylo/NeXML/Meta.pm \
	lib/Bio/Phylo/NeXML/Writable.pm \
	blib/lib/Bio/Phylo/NeXML/Writable.pm \
	lib/Bio/Phylo/Treedrawer/Gif.pm \
	blib/lib/Bio/Phylo/Treedrawer/Gif.pm \
	lib/Bio/Phylo/Parsers/Nexml.pm \
	blib/lib/Bio/Phylo/Parsers/Nexml.pm \
	lib/Bio/Phylo/Parsers/Taxlist.pm \
	blib/lib/Bio/Phylo/Parsers/Taxlist.pm \
	lib/Bio/Phylo/Forest/DrawNode.pm \
	blib/lib/Bio/Phylo/Forest/DrawNode.pm \
	lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	blib/lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	lib/Bio/Phylo/Treedrawer/Abstract.pm \
	blib/lib/Bio/Phylo/Treedrawer/Abstract.pm \
	lib/Bio/Phylo/Unparsers/Newick.pm \
	blib/lib/Bio/Phylo/Unparsers/Newick.pm \
	lib/Bio/Phylo/Matrices/Datum.pm \
	blib/lib/Bio/Phylo/Matrices/Datum.pm \
	lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	blib/lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	blib/lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	lib/Bio/Phylo/NeXML/DOM/Element.pm \
	blib/lib/Bio/Phylo/NeXML/DOM/Element.pm \
	lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	blib/lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	lib/Bio/Phylo/Unparsers/Pagel.pm \
	blib/lib/Bio/Phylo/Unparsers/Pagel.pm \
	lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	blib/lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	lib/Bio/Phylo/Factory.pm \
	blib/lib/Bio/Phylo/Factory.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 6.56
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = COPY_EXTENDED_ATTRIBUTES_DISABLE=1 COPYFILE_DISABLE=1 tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip -9f
SUFFIX = gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = Bio-Phylo
DISTVNAME = Bio-Phylo-0.34


# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	lib/Bio/Phylo/Parsers/Abstract.pm \
	lib/Bio/Phylo/Forest/Node.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	lib/Bio/Phylo/Util/IDPool.pm \
	lib/Bio/Phylo/Taxa/Taxon.pm \
	lib/Bio/Phylo/Taxa.pm \
	lib/Bio/Phylo/Unparsers/Mrp.pm \
	lib/Bio/Phylo/EvolutionaryModels.pm \
	lib/Bio/Phylo/Parsers/Phylip.pm \
	lib/Bio/Phylo/IO.pm \
	lib/Bio/Phylo/Treedrawer/Canvas.pm \
	lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	lib/Bio/Phylo/Util/Exceptions.pm \
	lib/Bio/Phylo/Util/CONSTANT.pm \
	lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	lib/Bio/Phylo/Unparsers/Nexml.pm \
	lib/Bio/Phylo/Matrices/Matrix.pm \
	lib/Bio/Phylo/Parsers/Table.pm \
	lib/Bio/Phylo/Treedrawer/Pdf.pm \
	lib/Bio/Phylo/Listable.pm \
	lib/Bio/Phylo/Generator.pm \
	lib/Bio/Phylo/Matrices/Datatype.pm \
	lib/Bio/Phylo/Treedrawer/Svg.pm \
	lib/Bio/Phylo/Util/StackTrace.pm \
	lib/Bio/Phylo/Parsers/Tolweb.pm \
	lib/Bio/Phylo/NeXML/DOM/Document.pm \
	lib/Bio/Phylo/Treedrawer.pm \
	lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	lib/Bio/Phylo.pm \
	lib/Bio/Phylo/Forest/Tree.pm \
	lib/Bio/Phylo/Unparsers/Nexus.pm \
	lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	lib/Bio/Phylo/Identifiable.pm \
	lib/Bio/Phylo/Forest/DrawTree.pm \
	lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	lib/Bio/Phylo/Util/Logger.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	lib/Bio/Phylo/Unparsers/Abstract.pm \
	lib/Bio/Phylo/Forest.pm \
	lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	lib/Bio/Phylo/Parsers/Nexus.pm \
	lib/Bio/Phylo/Matrices.pm \
	lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	lib/Bio/Phylo/Treedrawer/Swf.pm \
	lib/Bio/Phylo/NeXML/DOM.pm \
	lib/Bio/Phylo/Project.pm \
	lib/Bio/Phylo/Manual.pod \
	lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	lib/Bio/Phylo/Parsers/Fasta.pm \
	lib/Bio/Phylo/Treedrawer/Png.pm \
	lib/Bio/Phylo/Parsers/Newick.pm \
	lib/Bio/Phylo/Set.pm \
	lib/Bio/Phylo/Unparsers/Phylip.pm \
	lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	lib/Bio/Phylo/NeXML/Meta.pm \
	lib/Bio/Phylo/NeXML/Writable.pm \
	lib/Bio/Phylo/Treedrawer/Gif.pm \
	lib/Bio/Phylo/Parsers/Nexml.pm \
	lib/Bio/Phylo/Parsers/Taxlist.pm \
	lib/Bio/Phylo/Forest/DrawNode.pm \
	lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	lib/Bio/Phylo/Treedrawer/Abstract.pm \
	lib/Bio/Phylo/Unparsers/Newick.pm \
	lib/Bio/Phylo/Matrices/Datum.pm \
	lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	lib/Bio/Phylo/NeXML/DOM/Element.pm \
	lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	lib/Bio/Phylo/Unparsers/Pagel.pm \
	lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	lib/Bio/Phylo/Factory.pm
	$(NOECHO) $(POD2MAN) --section=3 --perm_rw=$(PERM_RW) \
	  lib/Bio/Phylo/Parsers/Abstract.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Abstract.$(MAN3EXT) \
	  lib/Bio/Phylo/Forest/Node.pm $(INST_MAN3DIR)/Bio::Phylo::Forest::Node.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Document::Libxml.$(MAN3EXT) \
	  lib/Bio/Phylo/Util/IDPool.pm $(INST_MAN3DIR)/Bio::Phylo::Util::IDPool.$(MAN3EXT) \
	  lib/Bio/Phylo/Taxa/Taxon.pm $(INST_MAN3DIR)/Bio::Phylo::Taxa::Taxon.$(MAN3EXT) \
	  lib/Bio/Phylo/Taxa.pm $(INST_MAN3DIR)/Bio::Phylo::Taxa.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Mrp.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Mrp.$(MAN3EXT) \
	  lib/Bio/Phylo/EvolutionaryModels.pm $(INST_MAN3DIR)/Bio::Phylo::EvolutionaryModels.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Phylip.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Phylip.$(MAN3EXT) \
	  lib/Bio/Phylo/IO.pm $(INST_MAN3DIR)/Bio::Phylo::IO.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Canvas.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Canvas.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Standard.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Standard.$(MAN3EXT) \
	  lib/Bio/Phylo/Util/Exceptions.pm $(INST_MAN3DIR)/Bio::Phylo::Util::Exceptions.$(MAN3EXT) \
	  lib/Bio/Phylo/Util/CONSTANT.pm $(INST_MAN3DIR)/Bio::Phylo::Util::CONSTANT.$(MAN3EXT) \
	  lib/Bio/Phylo/Taxa/TaxaLinker.pm $(INST_MAN3DIR)/Bio::Phylo::Taxa::TaxaLinker.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Nexml.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Nexml.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Matrix.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Matrix.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Table.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Table.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Pdf.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Pdf.$(MAN3EXT) \
	  lib/Bio/Phylo/Listable.pm $(INST_MAN3DIR)/Bio::Phylo::Listable.$(MAN3EXT) \
	  lib/Bio/Phylo/Generator.pm $(INST_MAN3DIR)/Bio::Phylo::Generator.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Svg.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Svg.$(MAN3EXT) \
	  lib/Bio/Phylo/Util/StackTrace.pm $(INST_MAN3DIR)/Bio::Phylo::Util::StackTrace.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Tolweb.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Tolweb.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Document.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Document.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Dna.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Dna.$(MAN3EXT) \
	  lib/Bio/Phylo.pm $(INST_MAN3DIR)/Bio::Phylo.$(MAN3EXT) \
	  lib/Bio/Phylo/Forest/Tree.pm $(INST_MAN3DIR)/Bio::Phylo::Forest::Tree.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Nexus.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Nexus.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Custom.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Custom.$(MAN3EXT) \
	  lib/Bio/Phylo/Identifiable.pm $(INST_MAN3DIR)/Bio::Phylo::Identifiable.$(MAN3EXT) \
	  lib/Bio/Phylo/Forest/DrawTree.pm $(INST_MAN3DIR)/Bio::Phylo::Forest::DrawTree.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Mixed.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Mixed.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Rna.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Rna.$(MAN3EXT) \
	  lib/Bio/Phylo/Util/Logger.pm $(INST_MAN3DIR)/Bio::Phylo::Util::Logger.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Element::Twig.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Abstract.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Abstract.$(MAN3EXT) \
	  lib/Bio/Phylo/Forest.pm $(INST_MAN3DIR)/Bio::Phylo::Forest.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Document::Twig.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Nexus.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Nexus.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/TypeSafeData.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::TypeSafeData.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Swf.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Swf.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM.$(MAN3EXT) \
	  lib/Bio/Phylo/Project.pm $(INST_MAN3DIR)/Bio::Phylo::Project.$(MAN3EXT) \
	  lib/Bio/Phylo/Manual.pod $(INST_MAN3DIR)/Bio::Phylo::Manual.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Protein.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Protein.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Fasta.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Fasta.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Png.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Png.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Newick.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Newick.$(MAN3EXT) \
	  lib/Bio/Phylo/Set.pm $(INST_MAN3DIR)/Bio::Phylo::Set.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Phylip.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Phylip.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Restriction.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Restriction.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/Meta.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::Meta.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/Writable.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::Writable.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Gif.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Gif.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Nexml.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Nexml.$(MAN3EXT) \
	  lib/Bio/Phylo/Parsers/Taxlist.pm $(INST_MAN3DIR)/Bio::Phylo::Parsers::Taxlist.$(MAN3EXT) \
	  lib/Bio/Phylo/Forest/DrawNode.pm $(INST_MAN3DIR)/Bio::Phylo::Forest::DrawNode.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Jpeg.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Jpeg.$(MAN3EXT) \
	  lib/Bio/Phylo/Treedrawer/Abstract.pm $(INST_MAN3DIR)/Bio::Phylo::Treedrawer::Abstract.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Newick.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Newick.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datum.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datum.$(MAN3EXT) \
	  lib/Bio/Phylo/Taxa/TaxonLinker.pm $(INST_MAN3DIR)/Bio::Phylo::Taxa::TaxonLinker.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Element::Libxml.$(MAN3EXT) \
	  lib/Bio/Phylo/Mediators/TaxaMediator.pm $(INST_MAN3DIR)/Bio::Phylo::Mediators::TaxaMediator.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/DOM/Element.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::DOM::Element.$(MAN3EXT) \
	  lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm $(INST_MAN3DIR)/Bio::Phylo::NeXML::Meta::XMLLiteral.$(MAN3EXT) \
	  lib/Bio/Phylo/Unparsers/Pagel.pm $(INST_MAN3DIR)/Bio::Phylo::Unparsers::Pagel.$(MAN3EXT) \
	  lib/Bio/Phylo/Matrices/Datatype/Continuous.pm $(INST_MAN3DIR)/Bio::Phylo::Matrices::Datatype::Continuous.$(MAN3EXT) \
	  lib/Bio/Phylo/Factory.pm $(INST_MAN3DIR)/Bio::Phylo::Factory.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  $(BASEEXT).x $(BOOTSTRAP) \
	  perl$(EXE_EXT) tmon.out \
	  *$(OBJ_EXT) pm_to_blib \
	  $(INST_ARCHAUTODIR)/extralibs.ld blibdirs.ts \
	  core.[0-9][0-9][0-9][0-9][0-9] *perl.core \
	  core.*perl.*.? $(MAKE_APERL_FILE) \
	  perl $(BASEEXT).def \
	  core.[0-9][0-9][0-9] mon.out \
	  lib$(BASEEXT).def perlmain.c \
	  perl.exe so_locations \
	  $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '--- #YAML:1.0' > META_new.yml
	$(NOECHO) $(ECHO) 'name:               Bio-Phylo' >> META_new.yml
	$(NOECHO) $(ECHO) 'version:            0.34' >> META_new.yml
	$(NOECHO) $(ECHO) 'abstract:           ~' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:' >> META_new.yml
	$(NOECHO) $(ECHO) '    - Rutger Vos' >> META_new.yml
	$(NOECHO) $(ECHO) 'license:            unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'distribution_type:  module' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    ExtUtils::MakeMaker:  0' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    ExtUtils::MakeMaker:  0' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:  {}' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '    directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '        - t' >> META_new.yml
	$(NOECHO) $(ECHO) '        - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by:       ExtUtils::MakeMaker version 6.56' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '    url:      http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '    version:  1.4' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old 



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"' --



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLARCHLIB)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install :: all
	$(NOECHO) $(MOD_INSTALL) \
		read $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLVENDORARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLPRIVLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod

doc_vendor_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLARCHLIB)/perllocal.pod
	-$(NOECHO) $(MKPATH) $(DESTINSTALLARCHLIB)
	-$(NOECHO) $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLVENDORLIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLARCHLIB)/perllocal.pod


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::
	$(NOECHO) $(UNINSTALL) $(PERL_ARCHLIB)/auto/$(FULLEXT)/.packlist

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::
	$(NOECHO) $(UNINSTALL) $(VENDORARCHEXP)/auto/$(FULLEXT)/.packlist


# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /opt/local/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE) subdirs-test

subdirs-test ::
	$(NOECHO) $(NOOP)


test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="0.34">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR>Rutger Vos</AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="darwin-2level-5.8" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  lib/Bio/Phylo/Parsers/Abstract.pm blib/lib/Bio/Phylo/Parsers/Abstract.pm \
	  lib/Bio/Phylo/Forest/Node.pm blib/lib/Bio/Phylo/Forest/Node.pm \
	  lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm blib/lib/Bio/Phylo/NeXML/DOM/Document/Libxml.pm \
	  lib/Bio/Phylo/Util/IDPool.pm blib/lib/Bio/Phylo/Util/IDPool.pm \
	  lib/Bio/Phylo/Taxa/Taxon.pm blib/lib/Bio/Phylo/Taxa/Taxon.pm \
	  lib/Bio/Phylo/Taxa.pm blib/lib/Bio/Phylo/Taxa.pm \
	  lib/Bio/Phylo/Unparsers/Mrp.pm blib/lib/Bio/Phylo/Unparsers/Mrp.pm \
	  lib/Bio/Phylo/EvolutionaryModels.pm blib/lib/Bio/Phylo/EvolutionaryModels.pm \
	  lib/Bio/Phylo/Parsers/Phylip.pm blib/lib/Bio/Phylo/Parsers/Phylip.pm \
	  lib/Bio/Phylo/IO.pm blib/lib/Bio/Phylo/IO.pm \
	  lib/Bio/Phylo/Treedrawer/Canvas.pm blib/lib/Bio/Phylo/Treedrawer/Canvas.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Standard.pm blib/lib/Bio/Phylo/Matrices/Datatype/Standard.pm \
	  lib/Bio/Phylo/Util/Exceptions.pm blib/lib/Bio/Phylo/Util/Exceptions.pm \
	  lib/Bio/Phylo/Util/CONSTANT.pm blib/lib/Bio/Phylo/Util/CONSTANT.pm \
	  lib/Bio/Phylo/Unparsers/Nexml.pm blib/lib/Bio/Phylo/Unparsers/Nexml.pm \
	  lib/Bio/Phylo/Taxa/TaxaLinker.pm blib/lib/Bio/Phylo/Taxa/TaxaLinker.pm \
	  lib/Bio/Phylo/Parsers/Table.pm blib/lib/Bio/Phylo/Parsers/Table.pm \
	  lib/Bio/Phylo/Matrices/Matrix.pm blib/lib/Bio/Phylo/Matrices/Matrix.pm \
	  lib/Bio/Phylo/Treedrawer/Pdf.pm blib/lib/Bio/Phylo/Treedrawer/Pdf.pm \
	  lib/Bio/Phylo/Listable.pm blib/lib/Bio/Phylo/Listable.pm \
	  lib/Bio/Phylo/Generator.pm blib/lib/Bio/Phylo/Generator.pm \
	  lib/Bio/Phylo/Matrices/Datatype.pm blib/lib/Bio/Phylo/Matrices/Datatype.pm \
	  lib/Bio/Phylo/Treedrawer/Svg.pm blib/lib/Bio/Phylo/Treedrawer/Svg.pm \
	  lib/Bio/Phylo/Util/StackTrace.pm blib/lib/Bio/Phylo/Util/StackTrace.pm \
	  lib/Bio/Phylo/Parsers/Tolweb.pm blib/lib/Bio/Phylo/Parsers/Tolweb.pm \
	  lib/Bio/Phylo/NeXML/DOM/Document.pm blib/lib/Bio/Phylo/NeXML/DOM/Document.pm \
	  lib/Bio/Phylo/Treedrawer.pm blib/lib/Bio/Phylo/Treedrawer.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Dna.pm blib/lib/Bio/Phylo/Matrices/Datatype/Dna.pm \
	  lib/Bio/Phylo.pm blib/lib/Bio/Phylo.pm \
	  lib/Bio/Phylo/Forest/Tree.pm blib/lib/Bio/Phylo/Forest/Tree.pm \
	  lib/Bio/Phylo/Unparsers/Nexus.pm blib/lib/Bio/Phylo/Unparsers/Nexus.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Custom.pm blib/lib/Bio/Phylo/Matrices/Datatype/Custom.pm \
	  lib/Bio/Phylo/Identifiable.pm blib/lib/Bio/Phylo/Identifiable.pm \
	  lib/Bio/Phylo/Forest/DrawTree.pm blib/lib/Bio/Phylo/Forest/DrawTree.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Mixed.pm blib/lib/Bio/Phylo/Matrices/Datatype/Mixed.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Rna.pm blib/lib/Bio/Phylo/Matrices/Datatype/Rna.pm \
	  lib/Bio/Phylo/Util/Logger.pm blib/lib/Bio/Phylo/Util/Logger.pm \
	  lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm blib/lib/Bio/Phylo/NeXML/DOM/Element/Twig.pm \
	  lib/Bio/Phylo/Unparsers/Abstract.pm blib/lib/Bio/Phylo/Unparsers/Abstract.pm \
	  lib/Bio/Phylo/Forest.pm blib/lib/Bio/Phylo/Forest.pm \
	  lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm blib/lib/Bio/Phylo/NeXML/DOM/Document/Twig.pm \
	  lib/Bio/Phylo/Parsers/Nexus.pm blib/lib/Bio/Phylo/Parsers/Nexus.pm \
	  lib/Bio/Phylo/Matrices.pm blib/lib/Bio/Phylo/Matrices.pm \
	  lib/Bio/Phylo/Matrices/TypeSafeData.pm blib/lib/Bio/Phylo/Matrices/TypeSafeData.pm \
	  lib/Bio/Phylo/Treedrawer/Swf.pm blib/lib/Bio/Phylo/Treedrawer/Swf.pm \
	  lib/Bio/Phylo/NeXML/DOM.pm blib/lib/Bio/Phylo/NeXML/DOM.pm \
	  lib/Bio/Phylo/Project.pm blib/lib/Bio/Phylo/Project.pm \
	  lib/Bio/Phylo/Manual.pod blib/lib/Bio/Phylo/Manual.pod \
	  lib/Bio/Phylo/Matrices/Datatype/Protein.pm blib/lib/Bio/Phylo/Matrices/Datatype/Protein.pm \
	  lib/Bio/Phylo/Parsers/Fasta.pm blib/lib/Bio/Phylo/Parsers/Fasta.pm \
	  lib/Bio/Phylo/Treedrawer/Png.pm blib/lib/Bio/Phylo/Treedrawer/Png.pm \
	  lib/Bio/Phylo/Parsers/Newick.pm blib/lib/Bio/Phylo/Parsers/Newick.pm \
	  lib/Bio/Phylo/Set.pm blib/lib/Bio/Phylo/Set.pm \
	  lib/Bio/Phylo/Unparsers/Phylip.pm blib/lib/Bio/Phylo/Unparsers/Phylip.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Restriction.pm blib/lib/Bio/Phylo/Matrices/Datatype/Restriction.pm \
	  lib/Bio/Phylo/NeXML/Meta.pm blib/lib/Bio/Phylo/NeXML/Meta.pm \
	  lib/Bio/Phylo/NeXML/Writable.pm blib/lib/Bio/Phylo/NeXML/Writable.pm \
	  lib/Bio/Phylo/Treedrawer/Gif.pm blib/lib/Bio/Phylo/Treedrawer/Gif.pm \
	  lib/Bio/Phylo/Parsers/Nexml.pm blib/lib/Bio/Phylo/Parsers/Nexml.pm \
	  lib/Bio/Phylo/Parsers/Taxlist.pm blib/lib/Bio/Phylo/Parsers/Taxlist.pm \
	  lib/Bio/Phylo/Forest/DrawNode.pm blib/lib/Bio/Phylo/Forest/DrawNode.pm \
	  lib/Bio/Phylo/Treedrawer/Jpeg.pm blib/lib/Bio/Phylo/Treedrawer/Jpeg.pm \
	  lib/Bio/Phylo/Treedrawer/Abstract.pm blib/lib/Bio/Phylo/Treedrawer/Abstract.pm \
	  lib/Bio/Phylo/Unparsers/Newick.pm blib/lib/Bio/Phylo/Unparsers/Newick.pm \
	  lib/Bio/Phylo/Matrices/Datum.pm blib/lib/Bio/Phylo/Matrices/Datum.pm \
	  lib/Bio/Phylo/Taxa/TaxonLinker.pm blib/lib/Bio/Phylo/Taxa/TaxonLinker.pm \
	  lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm blib/lib/Bio/Phylo/NeXML/DOM/Element/Libxml.pm \
	  lib/Bio/Phylo/Mediators/TaxaMediator.pm blib/lib/Bio/Phylo/Mediators/TaxaMediator.pm \
	  lib/Bio/Phylo/NeXML/DOM/Element.pm blib/lib/Bio/Phylo/NeXML/DOM/Element.pm \
	  lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm blib/lib/Bio/Phylo/NeXML/Meta/XMLLiteral.pm \
	  lib/Bio/Phylo/Unparsers/Pagel.pm blib/lib/Bio/Phylo/Unparsers/Pagel.pm \
	  lib/Bio/Phylo/Matrices/Datatype/Continuous.pm blib/lib/Bio/Phylo/Matrices/Datatype/Continuous.pm \
	  lib/Bio/Phylo/Factory.pm blib/lib/Bio/Phylo/Factory.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:


# End.
